name: .NET Core WinForms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Stalker.sln  
      Project_Path: Stalker.csproj  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore the application
      run: dotnet restore $env:Solution_Name

    - name: Build the application
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }} --runtime win-x64


    # Publish the application to a folder
    - name: Publish the application
      run: dotnet publish $env:Project_Path -c ${{ matrix.configuration }} -r win-x64 -o ./published

    # List the files in the published folder (for debugging)
    - name: List files in published folder
      run: |
        dir ./published

    # Upload the .exe file to GitHub Release
    - name: Upload .exe to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ secrets.VERSION }}
        files: ./published/Stalker.exe  # Path to the .exe file
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
